# TravisCI config file. See http://travis-ci.org
language: python
python:
  - 2.6
  - 2.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install pysqlite MySQL-python unittest2 mockito nose-exclude --use-mirrors
# command to run tests, e.g. python setup.py test
script: nosetests --where=tests --exclude-dir=tests/storage/
