# TravisCI config file. See http://travis-ci.org
language: python

python:
  - 2.7

# environment variables
env: MYSQL_TEST_HOST=127.0.0.1 MYSQL_TEST_USER=travis MYSQL_TEST_PASSWORD='' MYSQL_TEST_DB=b3_test POSTGRESQL_TEST_HOST=127.0.0.1 POSTGRESQL_TEST_USER=postgres POSTGRESQL_TEST_PASSWORD='' POSTGRESQL_TEST_DB=b3_test

addons:
  # select postgresql version
  postgresql: "9.3"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # downloads
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - if [ ! -f /downloads/sip.tar.gz ];   then curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.16/sip-4.16.tar.gz; fi
  - if [ ! -f /downloads/pyqt5.tar.gz ]; then curl -L -o /downloads/pyqt5.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.3/PyQt-gpl-5.3.tar.gz; fi
  # Qt5
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  # builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds
  - pushd /builds
  # SIP
  - tar xzf /downloads/sip.tar.gz --keep-newer-files
  - pushd sip-4.16
  - python configure.py
  - make -j5 && sudo make install
  - popd
  # PyQt5
  - tar xzf /downloads/pyqt5.tar.gz --keep-newer-files
  - pushd PyQt-gpl-5.3
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtWidgets
  - make -j5 && sudo make install
  - popd
  # builds complete
  - popd

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt
  - pip install -r test-requirements.txt
  - pip install -r build-requirements.txt

before_script:
  - psql -c "CREATE DATABASE b3_test WITH OWNER = postgres ENCODING = 'UTF8';" -U postgres

script: 
  - nosetests --where=tests --verbosity=3 --with-cov --cov b3 --cov-report term-missing --cov-config .coveragerc --exclude-dir-file=tests/exclude_dir.txt --exclude-test-file=tests/exclude_test.txt
  - nosetests --where=tests.plugins.poweradminbf3 --verbosity=3 --with-cov --cov b3.plugins.poweradminbf3 --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.poweradminurt --verbosity=3 --with-cov --cov b3.plugins.poweradminurt --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.urtserversidedemo --verbosity=3 --with-cov --cov b3.plugins.urtserversidedemo --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.test_callvote --verbosity=3 --with-cov --cov b3.plugins.callvote --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.test_firstkill --verbosity=3 --with-cov --cov b3.plugins.firstkill --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.test_jumper --verbosity=3 --with-cov --cov b3.plugins.jumper --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.test_spawnkill --verbosity=3 --with-cov --cov b3.plugins.spawnkill --cov-report term-missing --cov-config .coveragerc
  - py.test tests/plugins/makeroom
  - py.test tests/plugins/afk
  - python setup.py egg_info --tag-build .dev${TRAVIS_COMMIT:0:7} --tag-date sdist bdist_wheel
  - python setup.py build_exe

after_success:
  - pip install coveralls
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/489374443a557d989111
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
